### ISSUE TITLE
Fail to Exec Sql script containing json

### ISSUE THREAD

**Issue by jcourtat** [MarketSquare/Robotframework-Database-Library#111]
Hello

Reset postgreSQL database
    Connect To Database  psycopg2   ${DB_NAME}  ${DB_USER}  ${DB_PASSWORD}  ${DB}  ${DB_PORT}
    Log  Test access to database
    ${query}=  Query  SELECT obj_ref from d_object where obj_class_tag = '5B';
    Log  ${query}
    ${s}=  Format String  {}:{}:*:{}:{}  ${DB}  ${DB_PORT}  ${DB_USER}  ${DB_PASSWORD}
    Remove File     ~/.pgpass
    Append To File  ~/.pgpass  ${s}
    Run Process  chmod  600  ~/.pgpass  shell=True
    Run Process   psql    -U   ${DB_USER}  -h  ${DB}  -p  ${DB_PORT}  -f  ${DB_CONFIG_FILE}  -o  /tmp/reset_table tableX
    Execute Sql Script  ${DB_CONFIG_FILE}

If run from psql, the $DB_CONFIG_FILE runs successfully, if via Robotfm-DatabaseLibrary v1.1.1, it fails with message telling :
ProgrammingError: unterminated quoted string at or near "'{"name": "Proximity", "tags": "proximity "
LINE 1: ... 'getting in contact with them.', true, 'proxon', '{"name": ...

in my  $DB_CONFIG_FILE, the line that causes the error is:
INSERT INTO tableX.t_sensor ( sensorid, sensoruuid, shortname, fullname, description, enable, tags, jb_sensor ) VALUES ( 100, 'fe35b7ed-a899-4c98-827c-e4e8536524b2', 'Proximity', '', 'without getting in contact with them.', true, 'proximity;detection', '{"name": "Proximity", "tags": "proximity;detection", "description": "without getting in contact with them."}' );
Note that jb_sensor is a JSON type

Regards

**Comment by jerry57** [comment]
Do you mean to have a semi-colon between proximity and detection?  I believe this is what is causing the error.  If so, this is unfortunately a known issue that we have not resolved yet.  Can you try using the Query keyword in place of the Execute SQL Script, does it then work?

**Comment by jerry57** [comment]
Did using Query keyword resolve your issue?
