### ISSUE TITLE
Are there any plans to drop a new release?

### ISSUE THREAD

**Issue by adrianyorke** [MarketSquare/Robotframework-Database-Library#129]
We would like to take the latest release into our internal package library to include a patch that was merged Dec 2019 but we noticed that there has been no official release since Sep 19, 2018, v1.1.1.

Are there any plans to package a new release in the near future?

Thank you for considering this request.

**Comment by jerry57** [comment]
I will look into this.  In the meantime in the dist directory you should find a tarball of the latest code v1.2.4

**Comment by adrianyorke** [comment]
Thank you @jerry57.  We have done some internal work for IBM DB2 interaction.  I will find out more information and see if it's worth sharing with the community.

**Comment by amochin** [comment]
The library maintenance has been recently transferred to the Robot Framework community.
New releases are coming soon, although I can't tell any exact dates right now.
I believe this issue can be closed.
