### ISSUE TITLE
Error call procedure 

### ISSUE THREAD

**Issue by AndresPalacio** [MarketSquare/Robotframework-Database-Library#132]
error
None
Insert data into user table                                           | FAIL |
TypeError: 'as_dict' is an invalid keyword argument for this function

    ${spParams}        create list     1     Juan    123456       cr 56 # 45-23   new
    Set Test Variable   ${spName}   pruebatest.public.user_procedure
    ${QueryResults}     Call Stored Procedure   ${spName}   ${spParams}
    Log List    @{QueryResults}

**Comment by jerry57** [comment]
Connecting multiple times is not currently supported.  If you can get working and submit a pull request, that would be great.  Unfortunately I am  not able to work this at this time.

**Comment by jerry57** [comment]
What library are you using to connect to database?  Oracle (cx_Oracle) does not support "as_dict".

**Comment by AndresPalacio** [comment]
i am using psycopg2 2.8.4
 the error occurs on this line 

 cur = connection._dbconnection.cursor(as_dict=False)

**Comment by jerry57** [comment]
Please submit a PR with tests and I will evaluate it.

**Comment by MichalJirkatesena** [comment]
Hi, 
I need to call stored procedure by "Call Stored Procedure" keyword on sybase database. 

Unfortunately, Im still getting error: "TypeError: cursor() got an unexpected keyword argument "as_dict".
Is there any known solution for this problem?

Thank you.

**Comment by amochin** [comment]
Fixed in https://github.com/MarketSquare/Robotframework-Database-Library/commit/9f4d18f2b62578391f0e03e8e1b2d568cd45e5d2
