### ISSUE TITLE
[Question] How to log query result to robotframework report?

### ISSUE THREAD

**Issue by 4nif** [MarketSquare/Robotframework-Database-Library#147]
Hi

Is it possible to enable query log  in Robotframework report with the table header?
Using `Query` keyword only log the result without header

Thanks

**Comment by lucielavickova-tesena** [comment]
Voting up. I would also appreciate getting the SQL query result including the column headers.

**Comment by bhirsz** [comment]
The query results are often hard to read. I believe the best format would be HTML table. It is easy to generate without using external dependencies and it displays well in the RF log. We could add extra param like 'log_results=True' to handle it. There could be additional 'log_head' param to defined how much rows we want to log (ie default max 50, set to 0 to print all).

**Comment by amochin** [comment]
Implemented in version 2.0.0.
Logging looks like this: 
<img width="630" alt="image" src="https://github.com/user-attachments/assets/7412663a-4a03-40bd-bba1-9f3858d07d4e">
