### ISSUE TITLE
Update the READEME file

### ISSUE THREAD

**Issue by akhettar** [MarketSquare/Robotframework-Database-Library#158]
Hello there,

I am new to the RobotFramework. Could I kindly ask you to update the Readme file with the followings:

1. How to install the plugin
2. Sample Robot Test using SQL queries etc
3. How to configure connection details

Many thanks

Ayache

**Comment by amochin** [comment]
Fixed in https://github.com/MarketSquare/Robotframework-Database-Library/commit/3720a6be7ce90cf80fac21fb6f053bb58a0c6a7c
