### ISSUE TITLE
Call Stored Procedure with Python 3.10.6 and pymssql (2.2.7) return empty list 

### ISSUE THREAD

**Issue by skoroghly** [MarketSquare/Robotframework-Database-Library#161]
Call Stored Procedure with Python 3.10.6 and pymssql (2.2.7) return empty list 
but work fine with Python 3.9 and (2.2.5)

**Comment by amochin** [comment]
@skoroghly could you please provide more details about the issue?
Which procedure are you trying to call and which error message do you get?
Thanks.

**Comment by amochin** [comment]
Closing as there is not enough information to debug.
