### ISSUE TITLE
Provide custom error message to assertion keywords

### ISSUE THREAD

**Issue by robinmatz** [MarketSquare/Robotframework-Database-Library#162]
It would be a nice enhancement to be able to provide a custom error message to the keywords in assertion.py.

We have this feature in BuiltIn in `Should Be Equal`, `Should Be True`, and `Length Should Be`, to name a few.

We could introduce the same `msg` parameter to let the user provide a custom error message.

The following would be an example of this usage.

```robot
Row Count Is Equal To X    selectStatement   1    msg=my error message
```

I know you can work around this with `Query` and `Length Should Be `.

But wouldn't it be nice if the library provided this possibility out of the box?

**Comment by robinmatz** [comment]
Since this seems like an easy feature to implement, I can open a PR once I get to it.

**Comment by amochin** [comment]
I've just merged the pull request and copied the added tests into the new structure.
Thanks for your contribution, Robin! :)

**Comment by robinmatz** [comment]
Thanks alot for merging this. It is great to see that the development of this library has gained new momentum!
