### ISSUE TITLE
Support for SSL connections

### ISSUE THREAD

**Issue by restagner** [MarketSquare/Robotframework-Database-Library#164]
We are actively using the database-library across multiple projects within our company. It's been working flawlessly. We recently had one project's DB switch over to using SSL/TSL encryption.  Does the custom connection supported within the library support to connecting to a DB that uses SSL?

**Comment by trz-scoulibaly** [comment]
SSL/TLS is now a must have for all serious projects and not allowing TLS within the library will become more and more unbearable.

From what I read in https://github.com/PyMySQL/PyMySQL/blob/main/pymysql/connections.py, it looks like the SSL-related params are supported by connect() and hence could be used by DatabaseLibrary.

**Comment by restagner** [comment]
@trz-scoulibaly,

Thanks for the suggestion!!!
