### ISSUE TITLE
oracledb

### ISSUE THREAD

**Issue by martamedovova-ext91522** [MarketSquare/Robotframework-Database-Library#166]
Hello,
will you update your library for driver oracledb which uses thin and thick mode and now it is not possible to switch them :(

https://python-oracledb.readthedocs.io/en/latest/user_guide/appendix_c.html#connectdiffs

**Comment by joseajunior** [comment]
We need support for this library since from 3.11 and above cx_Oracle will no longer be supported.

**Comment by amochin** [comment]
Hello, the library maintenance was recently transferred to the Robot Framework community.
I'm currently working on updating it, but it's going to take some time to clean it all up.
Anyway - adding the native support of the new oracledb module is one of the highest priorities.

However you can use the new python oracledb even now - using the **Connect To Database Using Custom Params** keyword.
Here is an example:
```
*** Variables ***
${DBHost}       127.0.0.1
${DBName}       MY_DB
${DBPass}       pass
${DBPort}       1521
${DBUser}       db_user

*** Keywords ***
Connect To DB
    ${con_str} =    Catenate    SEPARATOR=${EMPTY}
    ...    ${DBUser}/${DBPass}@
    ...    ${DBHost}:${DBPort}/${DBName}
    Connect To Database Using Custom Params    oracledb    "${con_str}"
```

**Comment by martamedovova-ext91522** [comment]
Hi, 
great you added the oracledb mode. 
I cannot see the option for switching thin vs thick mode, is not includec then?
Thank you

**Comment by martamedovova-ext91522** [comment]
Welcome and thank you :-)
