### ISSUE TITLE
Improve publishing the keyword docs

### ISSUE THREAD

**Issue by amochin** [MarketSquare/Robotframework-Database-Library#172]
1. The keyword docs should be published somewhere in a way that opening a file in the github repo doesn't show the HTML code. Maybe publish them somewhere outside like e.g. in the [Browser Library](https://github.com/MarketSquare/robotframework-browser)?
2. Updating the published docs should occur automatically in a workflow - maybe in the same release pipeline as in #171 ?

**Comment by amochin** [comment]
Don't forget to update the link to the docs in the readme file!

**Comment by emanlove** [comment]
At a basic level this is what SeleniumLibrary is doing

```
from pathlib import Path

from invoke import task
from robot.libdoc import libdoc

@task
def kw_docs(ctx, version=None):
    """Generates the library keyword documentation.
    Args:
        version:  Appends version to the end of the filename.
                  Used for alpha and beta release.

     Documentation is generated by using the Libdoc tool.
    """
    if version:
        out = str(Path(f"docs/SeleniumLibrary-{version}.html"))
    else:
        out = str(Path("docs/SeleniumLibrary.html"))
    libdoc(str(Path("src/SeleniumLibrary")), out)
```    

Now this is using the invoke tool which several of the robot framework ecosystem projects and I think the core use to assist with admin / maintenance tasks like build and release. All it does is call the libdoc tool/executable that is part of the robot core which one could also do from the command line or terminal. Something like

```
$ git clone git@github.com:MarketSquare/Robotframework-Database-Library.git
$ cd Robotframework-Database-Library
$ libdoc src/DatabaseLibrary doc/DatabaseLibrary-demo.html
```
 I'll note the current version for SeleniumLibrary does a bit more in that it adds some analytics code and there are a few other tasks which help build a release. But for now I think even if you don't introduce tasks immediately (or ever) one could run libdoc as above.

**Comment by emanlove** [comment]
The SeleniumLibrary also uses github pages as a deployment host(?). That is where we publish documentation; both the readme as well as the keyword docs. It looks like the DatabaseLibrary is doing the same with the old pages Franz had published at https://marketsquare.github.io/Robotframework-Database-Library/.

**Comment by emanlove** [comment]
Relooking I see we publish the readme as the index.html on github pages using the following invoke task

```
from docutils.core import publish_cmdline

@task
def project_docs(ctx):
    """Generate project documentation.

    These docs are visible at http://robotframework.org/SeleniumLibrary/.
    """
    args = [
        "--stylesheet=style.css,extra.css",
        "--link-stylesheet",
        "README.rst",
        "docs/index.html",
    ]
    publish_cmdline(writer_name="html5", argv=args)
    print(Path(args[-1]).absolute())
```
which requires the addition package `docutils >= 0.14` which we install with the [requirements-dev.txt](https://github.com/robotframework/SeleniumLibrary/blob/master/requirements-dev.txt) set of packages.

**Comment by amochin** [comment]
Thanks @emanlove! I've created an Actions workflow, which uploads the docs html file on the Pages.
The Pages were already setup, but to be deployed from the special branch.
Now I changed it to be uploaded automatically after a push in the master branch.

The docs themselves are still to generate manually and then to upload in the repository folder "docs"
