### ISSUE TITLE
Recover docs from original Franz-see project

### ISSUE THREAD

**Issue by HelioGuilherme66** [MarketSquare/Robotframework-Database-Library#177]
Get the info from:
https://web.archive.org/web/20200118140939/http://franz-see.github.io/Robotframework-Database-Library/

**Comment by amochin** [comment]
Fixed in https://github.com/MarketSquare/Robotframework-Database-Library/commit/3720a6be7ce90cf80fac21fb6f053bb58a0c6a7c
