### ISSUE TITLE
New Oracledb driver - support switching to thick mode and back to thin mode

### ISSUE THREAD

**Issue by amochin** [MarketSquare/Robotframework-Database-Library#185]
See more infos here:
https://python-oracledb.readthedocs.io/en/latest/user_guide/initialization.html#initialization

**Comment by Rudolf-AT** [comment]
Hi,
you may be interested in the PR which adds support for oracledb "thick" mode:  [PR#189](https://github.com/MarketSquare/Robotframework-Database-Library/pull/189)

**Comment by amochin** [comment]
Done in #193.
However, there is a limitation - it's not possible to switch between thick and thin modes during a test execution session - even in different suites.

**Comment by Rudolf-AT** [comment]
Awesome! Thanks for all your work.
