### ISSUE TITLE
Use Python convention naming

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/Robotframework-Database-Library#188]
According to PEP8, Python uses snake_case naming for arguments. We follow Java-style camelCase instead:

```
def query(self, selectStatement, sansTran=False, returnAsDict=False):
```

Ideally, we should rename it to follow Python style. But because of the breaking nature of the change, I consider it as a low priority, low return change - so it's up to discussion. To help with deprecation period we could introduce special decorator that would catch 'old' names and warn users on rename:

```

def renamed_args():
    decorator that will change kwargs from old name to new name and warn user they need to update the code


@renamed_args(mapping={"selectStatement": "select_statement", ...})
def query(self, select_statement, sans_trans=False, return_as_dict=False):
```

**Comment by amochin** [comment]
Done in version 2.0.0
