### ISSUE TITLE
Handling multiple database connections

### ISSUE THREAD

**Issue by ZephyrusMB** [MarketSquare/Robotframework-Database-Library#199]
Hi,

following the example in the [documentation ](https://github.com/MarketSquare/Robotframework-Database-Library#handling-multiple-database-connections) I receive this error as output.

![image](https://github.com/MarketSquare/Robotframework-Database-Library/assets/81178328/6146911e-0a05-490d-8b69-a30ca3ece09a)

`Keyword 'DatabaseLibrary.Connect To Database' got unexpected named argument 'alias'.`

runned on 
Name: robotframework-databaselibrary
Version: 1.3.1
Summary: Database Library for Robot Framework

is this feature still supported?

**Comment by bhirsz** [comment]
It is new feature, introduced few days ago and still not released. It may be confusing since we also updated the README with the PR even if the change was not yet released.

@amochin I believe we should wrap up current release soon. We could avoid such problems if we were to use develop branch (feature -> develop or release -> master) but it would introduce unnecessary complexity as well so I guess it's fine as long as we remember to release if we updated documentation that is visible to everyone.

**Comment by ZephyrusMB** [comment]
Hi @bhirsz
thank you for the info, do you have any release date already?
kind regards

**Comment by amochin** [comment]
@ZephyrusMB please try the version 1.4.1, which was just released

**Comment by ZephyrusMB** [comment]
Hi @amochin 1.4.1 tested with the snippet in the first comment and **it worked** and the ticket can be close.
Thank you very much for the support and for this amazing feature.
I'm also using the driverMode=thick and it seems to work, also very useful feature.
this introduced a breaking change in our code and this may be a snippet to test a KO scenario

The code with v1.3.1 was
```
Evaluate    oracledb.init_oracle_client()    modules=oracledb
Connect To Database    dbapiModuleName=${db.module}
  ...    dbHost=${db.host}
  ...    dbPort=${db.port}
  ...    dbName=${db.name}
  ...    dbUsername=${credenziali}[username]
  ...    dbPassword=${credenziali}[password]
  ...    alias=alias
``` 
this produce the following exception with v1.4.1

`Suspended due to logged failure: Expected oracledb to run in thin mode: {oracle_thin_mode}, but the connection has thin mode: False`

solved adding driverMode=thick as parameter.

```
Evaluate    oracledb.init_oracle_client()    modules=oracledb
Connect To Database    dbapiModuleName=${db.module}
  ...    dbHost=${db.host}
  ...    dbPort=${db.port}
  ...    dbName=${db.name}
  ...    dbUsername=${credenziali}[username]
  ...    dbPassword=${credenziali}[password]
  ...    driverMode=thick
  ...    alias=alias
``` 


Kind regards

**Comment by amochin** [comment]
Thanks for your feedback, @ZephyrusMB!
I'll mention such kind of possible incompatibility in the release notes.

Basically you don't need this explicit init line anymore:
`Evaluate    oracledb.init_oracle_client()    modules=oracledb`
If you set the driverMode to thick, this init will be called in the library itself.
