### ISSUE TITLE
ProgrammingError: Unsupported parameter (Support for dict only): []

### ISSUE THREAD

**Issue by carlosnizolli** [MarketSquare/Robotframework-Database-Library#202]
I'm using the library to connect to Athena, it always worked but when updating to version 1.4.1 the error started to occur:
ProgrammingError: Unsupported parameter (Support for dict only): []

Connection:
![image](https://github.com/MarketSquare/Robotframework-Database-Library/assets/55762776/2be1d56f-3413-4b6c-beaa-24affd33a8ac)
Query:
![image](https://github.com/MarketSquare/Robotframework-Database-Library/assets/55762776/de9045f2-fb8e-4558-8902-71e7a5651be0)

pyathena==2.16.0
robotframework-databaselibrary==1.4.1

With version 1.3.1 it works normally

**Comment by amochin** [comment]
Hi @carlosnizolli , thanks for submitting the issue. I don’t think the library was ever tested with the Athena database… will see if I can reproduce it. 

In the meantime, could you please provide the full error message? Best would be to have the stack trace, produced when running tests with log level DEBUG or TRACE.

**Comment by carlosnizolli** [comment]
Hi @amochin 

FAIL	ProgrammingError: Unsupported parameter (Support for dict only): []	
14:28:32.501	DEBUG	Traceback (most recent call last):
  File "/home/carlos/.local/lib/python3.8/site-packages/DatabaseLibrary/query.py", line 81, in query
    self.__execute_sql(cur, selectStatement, parameters=parameters)
  File "/home/carlos/.local/lib/python3.8/site-packages/DatabaseLibrary/query.py", line 530, in __execute_sql
    return cur.execute(sql_statement, parameters)
  File "/home/carlos/.local/lib/python3.8/site-packages/pyathena/cursor.py", line 90, in execute
    self.query_id = self._execute(
  File "/home/carlos/.local/lib/python3.8/site-packages/pyathena/common.py", line 482, in _execute
    query = self._formatter.format(operation, parameters)
  File "/home/carlos/.local/lib/python3.8/site-packages/pyathena/formatter.py", line 203, in format
    raise ProgrammingError(
pyathena.error.ProgrammingError: Unsupported parameter (Support for dict only): []

**Comment by amochin** [comment]
@carlosnizolli could you please check if the [fix](https://github.com/MarketSquare/Robotframework-Database-Library/commit/336e1ca741a1ba677c4e68f57eb564d604feb714) works for you?
You can just copy the updated source code of **query.py** and replace it in your library installation.

**Comment by amochin** [comment]
@carlosnizolli good news, thanks for your feedback! The version 1.4.2 should be released in 1-2 weeks, before Christmas 😀
