### ISSUE TITLE
    Execute Sql String error with characters %

### ISSUE THREAD

**Issue by mit4ever** [MarketSquare/Robotframework-Database-Library#204]
Hi,

I have issue with keyword Execute Sql String 

robotframework-databaselibrary==1.4.1

```
    MySQL Connect
    ${sql}    Set variable    INSERT INTO testcase_info(test_case_id,testCaseName) VALUES ('1234','VAT 10% 5% no vat')
    Execute Sql String   ${sql}
    Disconnect from database
```
[FAIL] TypeError: not enough arguments for format string

but i install robotframework-databaselibrary-1.3.1 it work or remove charactor % work on 1.4.1
`  ${sql}    Set variable    INSERT INTO testcase_info(test_case_id,testCaseName) VALUES ('1234','VAT 10 5 no vat')`
Thanks

**Comment by bhirsz** [comment]
I believe our recent fix should cover it (which will be released in close future) - but we need to test it.

**Comment by bhirsz** [comment]
What database are you using? It happens because your database engine thinks you have parametrized query (though %) and tries to parametrize them. We pass parameteres as empty list instead of None (which was fixed). As workaround its probably possible to escape % characters

**Comment by tuyenlq** [comment]
Hi @bhirsz 

I using  mysql, to resolve the issue by installing a different version (1.3.1)

**Comment by amochin** [comment]
This should be fixed by the version 1.4.2 - could you please check and give a feedback?

**Comment by mit4ever** [comment]
@amochin 
Great 
I have tested and working on version 1.4.2
....
CLOSE TICKET

**Comment by amochin** [comment]
Thanks for the feedback @mit4ever !
